# Dependencies
markdown:         redcarpet
highlighter:      pygments
redcarpet: 
  extensions: ["tables"]

# Permalinks
permalink:        pretty

# Setup
title:            Blog - BS
tagline:          Data, hackery, stories
url:              http://blog.basilesimon.fr
description:      Basile Simon
# paginate:         1
# baseurl:          "/blog/"
author:
  name:           Basile Simon
  url:
  email:          basile@basilesimon.fr
local:            localhost:4000

# Custom vars
version:          1.0.0
github:           https://github.com/basilesimon
twitter:          https://twitter.com/basilesimon
projects:         http://projects.basilesimon.fr

# FTP
ftp_host:	'ftp.basilesimon.fr'
ftp_dir:	'blog'
ftp_passive:	false

keep_files: ["assets"]
