# Dependencies
markdown:         kramdown
highlighter:      rouge
redcarpet: 
  extensions: ["tables"]

# Permalinks
permalink:        pretty

# Setup
title:            Basile Simon (blog)
tagline:          Data, hackery, stories
url:              https://blog.basilesimon.fr
description:      Basile Simon's blog about data, visual journalism, and cycling in London
# paginate:         1
# baseurl:          "/blog/"
author:
  name:           Basile Simon
  email:          basile@basilesimon.fr
  twitter:        basilesimon
local:            localhost:4000
twitter:
  username:       basilesimon

# Custom vars
version:          1.0.0
github:           https://github.com/basilesimon
twitter:          https://twitter.com/basilesimon
projects:         https://basilesimon.fr

gems:
  - jekyll-seo-tag
plugins:
  - jekyll-seo-tag

keep_files: ["assets"]
