# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Blog
tagline:          Data, hackery, stories
url:              http://journalism.basilesimon.fr 
description:      Basile Simon
paginate:         1
baseurl:          /
author:
  name:           Basile Simon
  url:
  email:          basile@basilesimon.fr

# Custom vars
version:          1.0.0
github:           https://github.com/basilesimon
twitter:          https://twitter.com/basilesimon
projects:         http://projects.basilesimon.fr

# FTP
ftp_host:	'ftp.basilesimon.fr'
ftp_dir:	'journalism'
ftp_passive:	false

